services:
  static-app:
    depends_on:
      dynamodb-check:
        condition: service_completed_successfully
    build: .
    environment:
      - DYNAMODB_TABLE=stateful_aws_api_tasks
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      - DYNAMODB_AWS_REGION=local
      - API_PORT=9000
      - AWS_ACCESS_KEY_ID=DUMMYIDEXAMPLE
      - AWS_SECRET_ACCESS_KEY=DUMMYEXAMPLEKEY
    container_name: static-app
    ports:
      - "9000:9000"
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --spider --tries=1 http://localhost:9000/hello || exit 1"]
      interval: 10s
      timeout: 2s
      retries: 3

  # test:
  #   depends_on:
  #     app:
  #       condition: service_healthy
  #   image: node:slim
  #   command: ["echo", "ok"]

  static-test:
    depends_on:
      static-app:
        condition: service_healthy
    image: node:slim
    environment: 
      - BASE_URL=http://static-app:9000
    container_name: static-test
    volumes:
      - ./:/app
    working_dir: /app
    command: ["npm", "run", "ci-test"]
