services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    env_file:
      - .env
    container_name: dynamodb-local
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    healthcheck:
      test:
        - "CMD-SHELL"
        - 'curl -s -o /dev/null -I -w "%{http_code}" http://localhost:8000 | grep -q 400 || exit 1'
      interval: 1s
      timeout: 2s
      retries: 10

  dynamodb-setup:
    depends_on:
      dynamodb-local:
        condition: service_healthy
    image: amazon/aws-cli
    healthcheck:
      test:
        - "CMD-SHELL"
        - 'dynamodb describe-table --endpoint-url http://dynamodb-local:8000 --region $DYNAMODB_AWS_REGION --table-name $DYNAMODB_TABLE || exit 1'
      interval: 1s
      timeout: 2s
      retries: 10
    env_file:
      - .env
    container_name: dynamodb-setup
    command:
      dynamodb create-table --endpoint-url http://dynamodb-local:8000 --region $DYNAMODB_AWS_REGION --table-name $DYNAMODB_TABLE --billing-mode PAY_PER_REQUEST --key-schema AttributeName=id,KeyType=HASH --attribute-definitions AttributeName=id,AttributeType=S AttributeName=title,AttributeType=S --global-secondary-indexes "IndexName=IpIndex,KeySchema=[{AttributeName=title,KeyType=HASH}],Projection={ProjectionType=ALL}"
  
  app:
    depends_on:
      dynamodb-setup:
        condition: service_completed_successfully
    image: node:alpine
    env_file:
      - .env
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
    container_name: app
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --spider --tries=1 http://localhost:9000/hello || exit 1"]
      interval: 10s
      timeout: 2s
      retries: 3
    volumes:
      - ./:/app
    working_dir: /app
    command: ["npx", "nodemon", "./src/app.local.ts"]
    ports:
      - "9000:9000"

  test:
    depends_on:
      app:
        condition: service_healthy
    image: node:slim
    environment: 
      - BASE_URL=http://app:9000
    container_name: test
    volumes:
      - ./:/app
    working_dir: /app
    command: ["npx", "nodemon", "--watch", ".", "--ext", ".ts", "--exec", "npm", "test"]
