services:
  dev-app:
    depends_on:
      dynamodb-check:
        condition: service_completed_successfully
    image: node:alpine
    env_file: 
      - .env.local
    container_name: dev-app
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --spider --tries=1 http://localhost:9000/hello || exit 1"]
      interval: 10s
      timeout: 2s
      retries: 3
    volumes:
      - ./:/app
    working_dir: /app
    command: ["npx", "nodemon", "./src/app.local.ts"]

  dev-test:
    depends_on:
      dev-app:
        condition: service_healthy
    image: node:slim
    environment: 
      - BASE_URL=http://dev-app:9000
    container_name: dev-test
    volumes:
      - ./:/app
    working_dir: /app
    command: ["npx", "nodemon", "--watch", ".", "--ext", ".ts", "--exec", "npm", "test"]

