# https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.DownloadingAndRunning.html

services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    healthcheck:
      test:
        - "CMD-SHELL"
        - 'curl -s -o /dev/null -I -w "%{http_code}" http://localhost:8000 | grep -q 400 || exit 1'
      interval: 1s
      timeout: 2s
      retries: 10

  dynamodb-setup:
    depends_on:
      dynamodb-local:
        condition: service_healthy
    image: amazon/aws-cli
    environment:
      - AWS_PAGER=""
      - AWS_ACCESS_KEY_ID=DUMMYIDEXAMPLE
      - AWS_SECRET_ACCESS_KEY=DUMMYEXAMPLEKEY
      - DYNAMODB_TABLE=stateful_aws_api_tasks
    container_name: dynamodb-setup
    command:
      dynamodb create-table --endpoint-url http://dynamodb-local:8000 --region $DYNAMODB_REGION --table-name $DYNAMODB_TABLE --billing-mode PAY_PER_REQUEST --key-schema AttributeName=id,KeyType=HASH --attribute-definitions AttributeName=id,AttributeType=S AttributeName=title,AttributeType=S --global-secondary-indexes "IndexName=IpIndex,KeySchema=[{AttributeName=title,KeyType=HASH}],Projection={ProjectionType=ALL}"

  dynamodb-check:
    depends_on:
      dynamodb-setup:
        condition: service_completed_successfully
    image: amazon/aws-cli
    environment:
      - AWS_PAGER=""
      - AWS_ACCESS_KEY_ID=DUMMYIDEXAMPLE
      - AWS_SECRET_ACCESS_KEY=DUMMYEXAMPLEKEY
      - DYNAMODB_TABLE=stateful_aws_api_tasks
    container_name: dynamodb-check
    command:
      dynamodb describe-table --table-name $DYNAMODB_TABLE --region $DYNAMODB_REGION --endpoint-url http://dynamodb-local:8000 || exit 1