services:
  app:
    depends_on:
      - setup
    build: .
    env_file: 
      - .env.local
    container_name: app
    ports:
      - "9000:9000"
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --spider --tries=1 http://localhost:9000/hello || exit 1"]
      interval: 10s
      timeout: 2s
      retries: 3

  test:
    depends_on:
      app:
        condition: service_healthy
    image: node:slim
    command: ["echo", "ok"]

  # test:
  #   depends_on:
  #     app:
  #       condition: service_healthy
  #   image: node:slim
  #   environment: 
  #     - BASE_URL=http://localhost:9000
  #   container_name: test
  #   volumes:
  #     - ./:/app
  #   working_dir: /app
  #   command: ["echo", "run", "ci-test"]
